/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterList: typeof import("./src/components/RouterList.vue")["default"];
    RouterView: typeof import("vue-router")["RouterView"];
    Title: typeof import("./src/components/Title.vue")["default"];
  }
}
